host: localhost
port: 7001
metricsNameSnakeCase: true
queries:
  - key: name
    keyName: location
    prefix: wls_server_
    applicationRuntimes:
      key: name
      keyName: app
      componentRuntimes:
        prefix: wls_webapp_config_
        type: WebAppComponentRuntime
        key: name
        values: [deploymentState, contextRoot, sourceInfo, sessionsOpenedTotalCount, openSessionsCurrentCount, openSessionsHighCount]
        servlets:
          prefix: wls_servlet_
          key: servletName
  - JVMRuntime:
      prefix: wls_jvm_
      key: name
  - executeQueueRuntimes:
      prefix: wls_socketmuxer_
      key: name
      values: [pendingRequestCurrentCount]
  - workManagerRuntimes:
      prefix: wls_workmanager_
      key: name
      values: [stuckThreadCount, pendingRequests, completedRequests]
  - threadPoolRuntime:
      prefix: wls_threadpool_
      key: name
      values: [executeThreadTotalCount, queueLength, stuckThreadCount, hoggingThreadCount]
  - JDBCServiceRuntime:
      JDBCDataSourceRuntimeMBeans:
        prefix: wls_datasource_
        key: name

